### ISSUE TITLE
Can i have the Plugin?

### ISSUE THREAD

**Issue by supercrafti-lab** [XroixHD/Verify-Me#1]
Hi, can i have the Plugin? Thats MX Discord Name: supercrafter333#4062
Please contact me!

**Comment by xroix** [comment]
Sorry for the slow response.
I'll most certainly make this plugin public again because (as of today) the original server doesn't need it any more. However, I want to rewrite it before.

**Comment by SuperAdam47** [comment]
Ok i waitnhgyww
